image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - test

test-code:
  stage: test
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  script:
    - cargo test
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --ignore-tests --out Xml

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- --deny warnings

format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit-code:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit --deny warnings
