image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version
  services:
    - name: postgres:14-alpine

stages:
  - migrate
  - schema-check
  - test

migrate-db:
  stage: migrate
  variables:
    DATABASE_URL: postgres://postgres:password@postgres:5432/newsletter
  script:
    - apt-get install libpq-dev -y
    - SKIP_DOCKER=true ./scripts/init_db.sh

check-schema:
  stage: schema-check
  variables:
    DATABASE_URL: postgres://postgres:password@postgres:5432/newsletter
  script:
    - cargo sqlx prepare --check -- --bin newsletter

test-code:
  stage: test
  coverage: '/^\d+.\d+% coverage/'
  variables:
    DATABASE_URL: postgres://postgres:password@postgres:5432/newsletter
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  script:
    - cargo test
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --ignore-tests --out Xml

lint-code:
  stage: test
  variables:
    DATABASE_URL: postgres://postgres:password@postgres:5432/newsletter
  script:
    - rustup component add clippy
    - cargo clippy -- --deny warnings

format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit-code:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit --deny warnings
