application:
  port: 8000
  hmac_secret: long-and-very-secret-random-key-used-to-sign-flash-messagesvery-long
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "zero2prod"
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "aldo@aldofunes.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://localhost:6379"
